services:
  mcp-server:
    build:
      context: ./mcp_server_1
      dockerfile: Dockerfile
    image: mcp-server-enhanced
    container_name: mcp-server-enhanced
    environment:
      - DOCKER_CONTAINER=true
    ports:
      - "8000:8000"
    networks:
      - mcp-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  ngrok:
    image: ngrok/ngrok:latest
    container_name: mcp-ngrok
    restart: unless-stopped
    command: ["start", "--all", "--config", "/etc/ngrok.yml"]
    ports:
      - "4040:4040"  # ngrok web interface
    environment:
      - NGROK_AUTHTOKEN=32gC2d7iMt7zpEQgXLbwnyCnU6q_7ZvTLVs7RELZGG1E7WYDv
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml:ro
    networks:
      - mcp-network
    depends_on:
      - mcp-server
      - mcp-opensearch
      - tools-gateway
      - agentic-search
    profiles:
      - ngrok  # Only start when explicitly requested

  mcp-opensearch:
    build:
      context: ./mcp_opensearch
      dockerfile: Dockerfile
    image: mcp-opensearch-server
    container_name: mcp-opensearch-server
    environment:
      - DOCKER_CONTAINER=true
      - OPENSEARCH_URL=http://host.docker.internal:9200
    ports:
      - "8001:8001"
    networks:
      - mcp-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8001"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  tools-gateway:
    build:
      context: ./tools_gateway
      dockerfile: mcp_toolbox.dockerfile
    container_name: tools-gateway
    environment:
      - DOCKER_CONTAINER=true
      - HOST=0.0.0.0
      - PORT=8021
    ports:
      - "8021:8021"
    networks:
      - mcp-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8021/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    volumes:
      - ./tools_gateway/data:/app/data

  agentic-search:
    build:
      context: ./agentic_search
      dockerfile: Dockerfile
    container_name: agentic-search
    environment:
      - DOCKER_CONTAINER=true
      - HOST=0.0.0.0
      - PORT=8023
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - MCP_REGISTRY_URL=http://tools-gateway:8021
    ports:
      - "8023:8023"
    networks:
      - mcp-network
    restart: unless-stopped
    depends_on:
      - tools-gateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8023/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mcp-network:
    driver: bridge