version: '3.8'

services:
  agentic-search:
    build: .
    ports:
      - "8023:8023"
    environment:
      - HOST=0.0.0.0
      - PORT=8023
    volumes:
      # Optional: Mount logs directory if needed
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8023/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - agentic-network

networks:
  agentic-network:
    driver: bridge